@HostAddress = http://localhost:5169

POST {{HostAddress}}/api/packages
Content-Type: application/json

{
  "description": "Laptop Gamer ultra pesada",
  "weightInKg": 4.5,
  "isFragile": true,
  "shipmentId": "11111111-1111-1111-1111-111111111111"
}

### --- COTIZACIÓN TERRESTRE ---
POST {{HostAddress}}/api/shipments/quote
Content-Type: application/json

{
  "shipmentType": "terrestre",
  "weightInKg": 10,
  "distanceInKm": 100
}

### --- COTIZACIÓN AÉREA ---
POST {{HostAddress}}/api/shipments/quote
Content-Type: application/json

{
  "shipmentType": "aereo",
  "weightInKg": 10,
  "distanceInKm": 100
}